language: node_js

node_js:
  - "9"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm run build-prod && npm publish"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ -release$
